name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: cerve-linux
          - os: windows-latest
            artifact_name: cerve-windows
          - os: macos-latest
            artifact_name: cerve-macos

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.6'

      # Create a build directory
      - name: Create build directory
        run: mkdir build

      # Configure the project in release mode
      - name: Configure CMake
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=Release ..

      # Build the project
      - name: Build project
        working-directory: ./build
        run: VERBOSE=1 cmake --build .

      # Package the executable
      - name: Package executable
        working-directory: ./build
        run: |
          mkdir -p release
          cp cerve release/ # Replace 'cerve' with your executable name
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a release.zip release/*
          else
            tar -czvf release.tar.gz release/
          fi

      # Upload artifacts for this OS
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/release.${{ runner.os == 'Windows' && 'zip' || 'tar.gz' }}
