name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0, v2.1.0, etc.
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: cerve-linux
          - os: macos-latest
            artifact_name: cerve-macos

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.6'

      # Create a build directory
      - name: Create build directory
        run: mkdir build

      # Configure the project in release mode
      - name: Configure CMake
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=Release ..

      # Build the project
      - name: Build project
        working-directory: ./build
        shell: bash
        run: VERBOSE=1 cmake --build .

      # Package the executable
      - name: Package executable
        working-directory: ./build
        shell: bash
        run: |
          mkdir -p release
          cp cerve release
          tar -czvf release.tar.gz release/

      # Upload artifacts for this OS
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/release.tar.gz
  create-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Download all artifacts from the build jobs
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ${{ matrix.artifact_name }}
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/${{ matrix.artifact_name }}/release.tar.gz