name: Build & Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*' # Triggers on tags like v1.0.0, v2.1.0, etc.
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: cerve-linux
          - os: macos-latest
            artifact_name: cerve-macos

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.6'

      # Create a build directory
      - name: Create build directory
        run: mkdir build

      # Configure the project in release mode
      - name: Configure CMake
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=Release ..

      # Build the project
      - name: Build project
        working-directory: ./build
        shell: bash
        run: VERBOSE=1 cmake --build .

      # Package the executable
      - name: Package executable
        working-directory: ./build
        shell: bash
        run: |
          mkdir -p release
          cp cerve release
          FILENAME="${{ matrix.artifact_name }}-${{ github.ref_name }}.tar.gz"
          tar -czvf $FILENAME -C release .

      # Upload artifacts for this OS
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.artifact_name }}.tar.gz"
          path: "./build/cerve-${{ matrix.os }}-${{ github.ref_name }}.tar.gz"

  create-release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Download all artifacts from the build jobs
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*.tar.gz'
          merge-multiple: true
      - name: List downloaded files
        run: ls -R artifacts/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
